# Degree Day Model parameters in TOML format
# This file is to debug the code
# This parameter file is used by OPRAM_main_program.jl

title = "Parameter file to debug the code"

[runtime]
nNodes = 3           # Number of compute nodes to use
save2file = true     # If true save the results to a JLD2 file
save1year = true     # if true save first year's results, otherwise
                     # save all years from simYear tp simYear+meaxYears-1


[paths]   # All paths are relative to the user's home directory
output =  "OPRAM//results"      # Folder to save model output
results = "OPRAM//results"      # Folder for importing model results
data = "DATA//OPRAM"                     # Folder for other model data
meteoIE = "DATA//OPRAM//Climate_JLD2"    # Folder containing meteo data for ROI
meteoNI =  "nothing"                     # Folder containing meteo data for NI

[inputData]   # Input data on the model grid and species params
speciesFile = "git_repos/OPRAM/data/species_parameters.csv"
gridFile = "git_repos/OPRAM/data/IE_grid_locations.csv"
countyDefs = "git_repos/OPRAM/data/granite_county_defs.csv"

[model]     # Parameters to define the model
simYears = [2022, 2023,2024]           # Years to run model
thirty_years = [1991, 2020]                # 30yr period to average
maxYears = 4         # Maximum number of years to complete insect development
lastMeteoYear = 2024  # The last year of meteo data
country = "IE"       # Can be "IE", "NI" or "AllIreland"
thinFactor = 1       # Factor to thin grid (2 = sample every 2 km, 5 = sample every 5km)
method = "triangle"   # degree-day algorithm ("sine","triangle","average")


# List species to simulate. Species with several life stages are grouped together. 
# This grouping only affects the programs OPRAM_calculate_average and OPRAM_calculate anomaly
speciesList = ["Agrilus anxius"]
