# Model parameters in TOML format

title = "Degree day model parameter file"

[runtime]
nNodes = 3           # Number of compute nodes to use
save2file = true     # If true save the full result to a JLD2 file


[paths]   # All paths are relative to the user's home directory
output =  "Desktop//OPRAM//results"      # Folder to save model output
data = "DATA//OPRAM"                     # Folder for other model data
meteoIE = "DATA//OPRAM//Climate_JLD2"    # Folder containing meteo data for ROI
meteoNI =  "nothing"                     # Folder containing meteo data for NI

[inputData]   # Input data on the model grid and species params
speciesFile = "git_repos/OPRAM/data/species_parameters.csv"
gridFile = "git_repos/OPRAM/data/IE_grid_locations.csv"

[model]     # Parameters to define the model
nReps = 10          # Number of replicates to run
#futurePeriod = ["2021-2050", "2041-2070"]  # Climate future period
#rcp = ["26","45","85"]                     # Climate future RCP
futurePeriod = ["2021-2050"]  # Climate future period
rcp = ["26", "45"]        # Climate future RCP
maxYears = 4         # Maximum number of years to complete insect development
country = "IE"       # Can be "IE", "NI" or "AllIreland"
thinFactor = 1       # Factor to thin grid (2 = sample every 2 km, 5 = sample every 5km)
speciesList = ["agrilus", "sexdentatus", "duplicatus", "cembrae"]
thirty_years = [1991, 2020]  # 30yr period to average

# speciesList = ["anxius","frugiperda", "duplicatus", "cembrae", "decemlineata", " halys", "typo"]

# Predefined species are:
#  :agrilus_anxius
#  :halyomorpha_halys
#  :ips_cembrae
#  :ips_duplicatus
#  :ips_sexdentatus
#  :ips_typographus
#  :leptinotarsa_decemlineata
#  :oulema_melanopus
#  :spodoptera_frugiperda
